export const fermentavelCarbon = [
  {
    nome: 'açúcar de cana refinado',
    fermentaveis: 1,
    solidos: 1,
    monossacarídios: '0,142',
    dissacarídios: '0,84',
    trissacarídios: '0,159',
    potencial: '1,042',
  },
  {
    nome: 'açúcar de milho',
    fermentaveis: 1,
    solidos: '0,9',
    monossacarídios: '0,091',
    dissacarídios: '0,99',
    trissacarídios: '0,0484',
    potencial: '1,04',
  },
  {
    nome: 'demerara',
    fermentaveis: '0,95',
    solidos: '0,98',
    monossacarídios: '0,141',
    dissacarídios: '0,83',
    trissacarídios: '0,171',
    potencial: '1,042',
  },
  {
    nome: 'mascavo',
    fermentaveis: '0,97',
    solidos: '0,95',
    monossacarídios: '0,141',
    dissacarídios: '0,88',
    trissacarídios: '0,08',
    potencial: '1,042',
  },
  {
    nome: 'mel',
    fermentaveis: '0,75',
    solidos: '0,8',
    monossacarídios: '0,68',
    dissacarídios: '0,08',
    trissacarídios: '0,10',
    potencial: '1,04',
  },
  {
    nome: 'DME',
    fermentaveis: '0,75',
    solidos: '0,8',
    monossacarídios: '0,14',
    dissacarídios: '0,68',
    trissacarídios: '0,185',
    potencial: '1,042',
  },
];
