export const ferm_db = [
  {
    Nome: 'Fermentação simples temperatura baixa',
    temp_1: 15,
    Dias: 'Até finalizar estabilizar a gravidade',
    tipo: 'Fermentação',
    temp_2: 22,
    dias: 'Até consumir o diacetil',
    tipo__1: 'Descanso do diacetil',
    temp_3: 0,
    dias__1: 'Até clarificar',
    tipo__2: 'Maturação',
    temp_4: '',
    dias__2: '',
    tipo__3: '',
    temp_5: '',
    dias__3: '',
    tipo__4: '',
    temp_6: '',
    dias__4: '',
    tipo__5: '',
  },
  {
    Nome: 'Fermentação simples temperatura media',
    temp_1: 17,
    Dias: 'Até finalizar estabilizar a gravidade',
    tipo: 'Fermentação',
    temp_2: 22,
    dias: 'Até consumir o diacetil',
    tipo__1: 'Descanso do diacetil',
    temp_3: 0,
    dias__1: 'Até clarificar',
    tipo__2: 'Maturação',
    temp_4: '',
    dias__2: '',
    tipo__3: '',
    temp_5: '',
    dias__3: '',
    tipo__4: '',
    temp_6: '',
    dias__4: '',
    tipo__5: '',
  },
  {
    Nome: 'Fermentação simples temperatura alta',
    temp_1: 20,
    Dias: 'Até finalizar estabilizar a gravidade',
    tipo: 'Fermentação',
    temp_2: 22,
    dias: 'Até consumir o diacetil',
    tipo__1: 'Descanso do diacetil',
    temp_3: 0,
    dias__1: 'Até clarificar',
    tipo__2: 'Maturação',
    temp_4: '',
    dias__2: '',
    tipo__3: '',
    temp_5: '',
    dias__3: '',
    tipo__4: '',
    temp_6: '',
    dias__4: '',
    tipo__5: '',
  },
  {
    Nome: 'Fermentação com dryhop',
    temp_1: 17,
    Dias: 'Até finalizar estabilizar a gravidade',
    tipo: 'Fermentação',
    temp_2: 22,
    dias: '2 dias',
    tipo__1: 'Descanso do diacetil',
    temp_3: 22,
    dias__1: 'Até consumir o diacetil',
    tipo__2: 'Maturação',
    temp_4: '',
    dias__2: '',
    tipo__3: '',
    temp_5: '',
    dias__3: '',
    tipo__4: '',
    temp_6: '',
    dias__4: '',
    tipo__5: '',
  },
  {
    Nome: 'Fermentação lager rápida',
    temp_1: 15,
    Dias: 'até seilá',
    tipo: 'Fermentação',
    temp_2: 17,
    dias: 'sei lá',
    tipo__1: 'Fermentação',
    temp_3: 19,
    dias__1: 'sei lá',
    tipo__2: 'Fermentação',
    temp_4: 20,
    dias__2: 'sei lá',
    tipo__3: 'Fermentação',
    temp_5: 22,
    dias__3: 'sei lá',
    tipo__4: 'Descanso do diacetil',
    temp_6: 0,
    dias__4: 'muito tempo',
    tipo__5: 'Laggering',
  },
];
