export const mash_db = [
  {
    nome: 'Decocção Mash, Dupla',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Used for some authentic German styles. Attempt to draw decoction from the thickest portion of the mash. Profiles vary. Some traditional German mashes use a long acid rest at 40 deg C. Also some sources recommend the decoction amount be given a 15 minute saccharification rest at 158 F (70 C) before boiling it.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Decocção Mash, Simples',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Used in some authentic German styles. Attempt to draw decoction from the thickest portion of the mash. Profiles vary. Some traditional German mashes use a long acid rest at 40 deg C. Also some sources recommend the decoction amount be given a 15 minute saccharification rest at 158 F (70 C) before boiling it.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Decocção Mash, Tripla',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Authentic Germany mash schedule. Attempt to draw decoction from the thickest portion of the mash. Some sources recommend that each decoction amount be given a 15 minute saccharification rest at 158 F (70 C) before boiling it.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Decocção Mash, Tripla, Lager',
    'Peso do grão': 353,
    'Temperatura do grão': 21,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 21,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Derived from Noonan, &amp;quot;New Brewing Lager Beer&amp;quot;. A pure infusion/decoction mash with no temperature steps. The book recommends adding boiling water for the second step, though it appears it would come in too high in temperature. \nThe first two decoctions are from the &amp;quot;heaviest&amp;quot; part of mash while the third is from the &amp;quot;thinnest&amp;quot;.\nHe also recommends you hold Dextrinization until it passes an iodine test (probably more than 20 minutes)',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Cheio - Infusão de Dupla',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'A full bodied mash profile for beers requiring a protein rest. Used for beer with large portions of unmodified adjuncts such as unmalted wheat.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Leve - Infusão de Dupla',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Double step infusion - for light body beers requiring a protein rest. Used primarily in beers high in unmodified grains or adjuncts.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Médio - Infusão de Dupla',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Double step infusion - for medium body beers requiring a protein rest. Used primarily in beers high in unmodified grains or adjuncts.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Infusão com Adjuntos Pré-Cozidos',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Long protein rests help to break down starches in precooked adjuncts in preparation for saccharification step.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Cheio - Infusão Simples',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES: 'Simple single infusion mash for use with most modern well modified grains (about 95% of the time).',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Cheio - Infusão Simples, Lavagem',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 1,
    'Porcentagem do batch': 90,
    MH_BATCH_EVEN: 1,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES: 'Simple single infusion mash for use with most modern well modified grains (about 95% of the time).',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Cheio - Infusão Simples, Sem Mash-out',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES: 'Simple single infusion mash for use with most modern well modified grains (about 95% of the time).',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Leve - Infusão Simples',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES: 'Simple single infusion mash for use with most modern well modified grains (about 95% of the time).',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Leve - Infusão Simples, Lavagem',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 1,
    'Porcentagem do batch': 90,
    MH_BATCH_EVEN: 1,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES: 'Simple single infusion mash for use with most modern well modified grains (about 95% of the time).',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Leve - Infusão Simples, Sem Mash-out',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES: 'Simple single infusion mash for use with most modern well modified grains (about 95% of the time).',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Médio - Infusão Simples',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES: 'Simple single infusion mash for use with most modern well modified grains (about 95% of the time).',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Médio - Infusão Simples, Lavagem',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 1,
    'Porcentagem do batch': 90,
    MH_BATCH_EVEN: 1,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES: 'Simple single infusion mash for use with most modern well modified grains (about 95% of the time).',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Médio - Infusão Simples, Sem Mash-out',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES: 'Simple single infusion mash for use with most modern well modified grains (about 95% of the time).',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Cheio - Mash por Temperatura, 1 Passo',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Temperature mash for use when mashing in a brew pot over a heat source such as the stove. Use heat to maintain desired temperature during the mash.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Leve - Mash por Temperatura, 1 Passo',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Temperature mash for use when mashing in a brew pot over a heat source such as the stove. Use heat to maintain desired temperature during the mash.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Médio - Mash por Temperatura, 1 Passo',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Temperature mash for use when mashing in a brew pot over a heat source such as the stove. Use heat to maintain desired temperature during the mash.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Cheio - Mash por Temperatura, 2 Passos',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Two step profile with a protein rest for mashes with unmodified grains or adjuncts. Temperature mash for use when mashing in a brew pot over a heat source such as the stove. Use heat to maintain desired temperature during the mash.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Leve - Mash por Temperatura, 2 Passos',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Two step profile with a protein rest for mashes with unmodified grains or adjuncts. Temperature mash for use when mashing in a brew pot over a heat source such as the stove. Use heat to maintain desired temperature during the mash.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Médio - Mash por Temperatura, 2 Passos',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,4',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 100,
    MH_BATCH_EVEN: 0,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 0,
    MH_NOTES:
      'Two step profile with a protein rest for mashes with unmodified grains or adjuncts. Temperature mash for use when mashing in a brew pot over a heat source such as the stove. Use heat to maintain desired temperature during the mash.',
    MH_EQUIP_ADJUST: 0,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 0,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Cheio - BIAB',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,2',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 95,
    MH_BATCH_EVEN: 1,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 1,
    MH_NOTES:
      'Brew in a bag method where the full boil volume is mashed within the boil vessel and then the grains are withdrawn at the end of the mash. No active sparging is required. This is a full body beer profile.',
    MH_EQUIP_ADJUST: 1,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 353,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Leve - BIAB',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,2',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 95,
    MH_BATCH_EVEN: 1,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 1,
    MH_NOTES:
      'Brew in a bag method where the full boil volume is mashed within the boil vessel and then the grains are withdrawn at the end of the mash. No active sparging is required. This is a light body beer profile.',
    MH_EQUIP_ADJUST: 1,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 353,
    MH_TUN_HC: 0,
  },
  {
    nome: 'Corpo Médio - BIAB',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,2',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 95,
    MH_BATCH_EVEN: 1,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 1,
    MH_NOTES:
      'Brew in a bag method where the full boil volume is mashed within the boil vessel and then the grains are withdrawn at the end of the mash. No active sparging is required. This is a medium body beer profile.',
    MH_EQUIP_ADJUST: 1,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 353,
    MH_TUN_HC: 0,
  },
  {
    nome: 'BIAB, Pilsner',
    'Peso do grão': 353,
    'Temperatura do grão': 22,
    MH_BOIL_TEMP: 100,
    MH_TUN_TEMP: 22,
    MH_PH: '5,2',
    MH_SPARGE_TEMP: '75,6',
    MH_BATCH: 0,
    'Porcentagem do batch': 95,
    MH_BATCH_EVEN: 1,
    'drenagem do mash': 0,
    MASH_39: 1,
    DEADSPACE: 0,
    MH_BIAB_VOL: '169,1',
    MH_BIAB: 1,
    MH_NOTES:
      'Brew in a bag method where the full boil volume is mashed within the boil vessel and then the grains are withdrawn at the end of the mash. No active sparging is required. This is a pilsner mash profile that can be used for styles requiring high attenuation and/or modification.',
    MH_EQUIP_ADJUST: 1,
    MH_TUN_VOL: 169,
    MH_TUN_MASS: 353,
    MH_TUN_HC: 0,
  },
];
