export const mashSteps_db = [
  {
    MashName: 'Decocção  Dupla',
    MashStep_F_MS_NAME: 'Proteica',
    STEP_TEMP: '50,00',
    _STEP_TIME: 35,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '52,53',

    MashStep_F_MS_NAME__1: 'Sacarificação (β)',
    STEP_TEMP__1: 64,
    _STEP_TIME__1: 20,
    MS_RISE_TIME__1: 2,
    MS_INFUSION_TEMP__1: '',
    __1: '',
    MashStep_F_MS_NAME__2: 'Sacarificação (α)',
    STEP_TEMP__2: '68,89',
    _STEP_TIME__2: 20,
    MS_RISE_TIME__2: 2,
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: 'Mash Out',
    STEP_TEMP__3: '75,56',
    _STEP_TIME__3: 10,
    MS_RISE_TIME__3: 10,
    MS_INFUSION_TEMP__3: '76,67',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Decocção  Simples',
    MashStep_F_MS_NAME: 'Proteica',
    STEP_TEMP: '50,00',
    _STEP_TIME: 35,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '52,53',

    MashStep_F_MS_NAME__1: 'Sacarificação',
    STEP_TEMP__1: 68,
    _STEP_TIME__1: 45,
    MS_RISE_TIME__1: 2,
    MS_INFUSION_TEMP__1: '',
    __1: '',
    MashStep_F_MS_NAME__2: 'Mash Out',
    STEP_TEMP__2: '75,56',
    _STEP_TIME__2: 10,
    MS_RISE_TIME__2: 10,
    MS_INFUSION_TEMP__2: '76,67',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Decocção  Tripla',
    MashStep_F_MS_NAME: 'Acidificação',
    STEP_TEMP: '35,00',
    _STEP_TIME: 45,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '36,16',

    MashStep_F_MS_NAME__1: 'Proteica',
    STEP_TEMP__1: 50,
    _STEP_TIME__1: 60,
    MS_RISE_TIME__1: 2,
    MS_INFUSION_TEMP__1: '',
    __1: '',
    MashStep_F_MS_NAME__2: 'Sacarificação (β)',
    STEP_TEMP__2: '64,44',
    _STEP_TIME__2: 15,
    MS_RISE_TIME__2: 2,
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: 'Sacarificação (α)',
    STEP_TEMP__3: '68,89',
    _STEP_TIME__3: 15,
    MS_RISE_TIME__3: 2,
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: 'Mash Out',
    STEP_TEMP__4: '75,56',
    _STEP_TIME__4: 10,
    MS_RISE_TIME__4: 10,
    MS_INFUSION_TEMP__4: '76,67',
  },
  {
    MashName: 'Decocção  Tripla, Lager',
    MashStep_F_MS_NAME: 'Infusão',
    STEP_TEMP: '21,11',
    _STEP_TIME: 15,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '21,11',

    MashStep_F_MS_NAME__1: 'Acidificação',
    STEP_TEMP__1: 41,
    _STEP_TIME__1: 20,
    MS_RISE_TIME__1: 2,
    MS_INFUSION_TEMP__1: '74,22',
    __1: '',
    MashStep_F_MS_NAME__2: 'Proteica',
    STEP_TEMP__2: '50,00',
    _STEP_TIME__2: 10,
    MS_RISE_TIME__2: 5,
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: 'Dextrinização',
    STEP_TEMP__3: '67,22',
    _STEP_TIME__3: 20,
    MS_RISE_TIME__3: 2,
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: 'Mash Out',
    STEP_TEMP__4: '76,67',
    _STEP_TIME__4: 5,
    MS_RISE_TIME__4: 5,
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Cheio - Infusão Dupla',
    MashStep_F_MS_NAME: 'Proteica',
    STEP_TEMP: '50,00',
    _STEP_TIME: 30,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '55,62',

    MashStep_F_MS_NAME__1: 'Sacarificação',
    STEP_TEMP__1: 69,
    _STEP_TIME__1: 30,
    MS_RISE_TIME__1: 2,
    MS_INFUSION_TEMP__1: '94,44',
    __1: '',
    MashStep_F_MS_NAME__2: 'Mash Out',
    STEP_TEMP__2: '75,56',
    _STEP_TIME__2: 10,
    MS_RISE_TIME__2: 2,
    MS_INFUSION_TEMP__2: '96,47',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Leve - Infusão Dupla',
    MashStep_F_MS_NAME: 'Proteica',
    STEP_TEMP: '50,00',
    _STEP_TIME: 30,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '55,62',

    MashStep_F_MS_NAME__1: 'Sacarificação',
    STEP_TEMP__1: 64,
    _STEP_TIME__1: 30,
    MS_RISE_TIME__1: 2,
    MS_INFUSION_TEMP__1: '83,98',
    __1: '',
    MashStep_F_MS_NAME__2: 'Mash Out',
    STEP_TEMP__2: '75,56',
    _STEP_TIME__2: 10,
    MS_RISE_TIME__2: 2,
    MS_INFUSION_TEMP__2: '98,79',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Médio - Infusão Dupla',
    MashStep_F_MS_NAME: 'Proteica',
    STEP_TEMP: '50,00',
    _STEP_TIME: 30,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '55,62',

    MashStep_F_MS_NAME__1: 'Sacarificação',
    STEP_TEMP__1: 67,
    _STEP_TIME__1: 30,
    MS_RISE_TIME__1: 2,
    MS_INFUSION_TEMP__1: '89,21',
    __1: '',
    MashStep_F_MS_NAME__2: 'Mash Out',
    STEP_TEMP__2: '75,56',
    _STEP_TIME__2: 10,
    MS_RISE_TIME__2: 2,
    MS_INFUSION_TEMP__2: '99,46',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Infusão com Adjuntos Pré-Cozidos',
    MashStep_F_MS_NAME: 'Proteica',
    STEP_TEMP: '40,00',
    _STEP_TIME: 30,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '44,05',

    MashStep_F_MS_NAME__1: 'Proteica',
    STEP_TEMP__1: 50,
    _STEP_TIME__1: 45,
    MS_RISE_TIME__1: 2,
    MS_INFUSION_TEMP__1: '82,74',
    __1: '',
    MashStep_F_MS_NAME__2: 'Sacarificação (β + α)',
    STEP_TEMP__2: '65,56',
    _STEP_TIME__2: 60,
    MS_RISE_TIME__2: 2,
    MS_INFUSION_TEMP__2: '94,05',
    __2: '',
    MashStep_F_MS_NAME__3: 'Mash Out',
    STEP_TEMP__3: '75,56',
    _STEP_TIME__3: 10,
    MS_RISE_TIME__3: 2,
    MS_INFUSION_TEMP__3: '97,58',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Cheio - Infusão Simples',
    MashStep_F_MS_NAME: 'Mash In (α +  β)',
    STEP_TEMP: '68,89',
    _STEP_TIME: 45,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '75,69',

    MashStep_F_MS_NAME__1: 'Mash Out',
    STEP_TEMP__1: 76,
    _STEP_TIME__1: 10,
    MS_RISE_TIME__1: 2,
    MS_INFUSION_TEMP__1: '94,65',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Cheio - Infusão Simples, Lavagem',
    MashStep_F_MS_NAME: 'Mash In (α +  β)',
    STEP_TEMP: '68,89',
    _STEP_TIME: 45,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '75,69',

    MashStep_F_MS_NAME__1: '',
    STEP_TEMP__1: '',
    _STEP_TIME__1: '',
    MS_RISE_TIME__1: '',
    MS_INFUSION_TEMP__1: '',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Cheio - Infusão Simples, Sem Mash-out',
    MashStep_F_MS_NAME: 'Mash In (α +  β)',
    STEP_TEMP: '68,89',
    _STEP_TIME: 45,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '75,69',

    MashStep_F_MS_NAME__1: '',
    STEP_TEMP__1: '',
    _STEP_TIME__1: '',
    MS_RISE_TIME__1: '',
    MS_INFUSION_TEMP__1: '',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Leve - Infusão Simples',
    MashStep_F_MS_NAME: 'Mash In ( β)',
    STEP_TEMP: '64,44',
    _STEP_TIME: 75,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '70,60',

    MashStep_F_MS_NAME__1: 'Mash Out',
    STEP_TEMP__1: 76,
    _STEP_TIME__1: 10,
    MS_RISE_TIME__1: 2,
    MS_INFUSION_TEMP__1: '95,45',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Leve - Infusão Simples, Lavagem',
    MashStep_F_MS_NAME: 'Mash In (β)',
    STEP_TEMP: '64,44',
    _STEP_TIME: 75,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '70,60',

    MashStep_F_MS_NAME__1: '',
    STEP_TEMP__1: '',
    _STEP_TIME__1: '',
    MS_RISE_TIME__1: '',
    MS_INFUSION_TEMP__1: '',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Leve - Infusão Simples, Sem Mash-out',
    MashStep_F_MS_NAME: 'Mash In (β)',
    STEP_TEMP: '64,44',
    _STEP_TIME: 75,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '70,60',

    MashStep_F_MS_NAME__1: '',
    STEP_TEMP__1: '',
    _STEP_TIME__1: '',
    MS_RISE_TIME__1: '',
    MS_INFUSION_TEMP__1: '',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Médio - Infusão Simples',
    MashStep_F_MS_NAME: 'Mash In (β + α)',
    STEP_TEMP: '66,67',
    _STEP_TIME: 60,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '73,14',

    MashStep_F_MS_NAME__1: 'Mash Out',
    STEP_TEMP__1: 76,
    _STEP_TIME__1: 10,
    MS_RISE_TIME__1: 2,
    MS_INFUSION_TEMP__1: '93,74',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Médio - Infusão Simples, Lavagem',
    MashStep_F_MS_NAME: 'Mash In (β + α)',
    STEP_TEMP: '66,67',
    _STEP_TIME: 60,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '73,14',

    MashStep_F_MS_NAME__1: '',
    STEP_TEMP__1: '',
    _STEP_TIME__1: '',
    MS_RISE_TIME__1: '',
    MS_INFUSION_TEMP__1: '',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Médio - Infusão Simples, Sem Mash-out',
    MashStep_F_MS_NAME: 'Mash In (β + α)',
    STEP_TEMP: '66,67',
    _STEP_TIME: 60,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '73,14',

    MashStep_F_MS_NAME__1: '',
    STEP_TEMP__1: '',
    _STEP_TIME__1: '',
    MS_RISE_TIME__1: '',
    MS_INFUSION_TEMP__1: '',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Cheio - Mash por Temperatura, 1 Passo',
    MashStep_F_MS_NAME: 'Sacarificação (β + α)',
    STEP_TEMP: '68,89',
    _STEP_TIME: 40,
    MS_RISE_TIME: 15,
    MS_INFUSION_TEMP: '75,69',

    MashStep_F_MS_NAME__1: 'Mash Out',
    STEP_TEMP__1: 76,
    _STEP_TIME__1: 10,
    MS_RISE_TIME__1: 10,
    MS_INFUSION_TEMP__1: '83,33',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Leve - Mash por Temperatura, 1 Passo',
    MashStep_F_MS_NAME: 'Sacarificação (β + α)',
    STEP_TEMP: '64,44',
    _STEP_TIME: 75,
    MS_RISE_TIME: 15,
    MS_INFUSION_TEMP: '70,60',

    MashStep_F_MS_NAME__1: 'Mash Out',
    STEP_TEMP__1: 76,
    _STEP_TIME__1: 10,
    MS_RISE_TIME__1: 10,
    MS_INFUSION_TEMP__1: '83,33',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Médio - Mash por Temperatura, 1 Passo',
    MashStep_F_MS_NAME: 'Sacarificação (β + α)',
    STEP_TEMP: '66,67',
    _STEP_TIME: 60,
    MS_RISE_TIME: 15,
    MS_INFUSION_TEMP: '73,14',

    MashStep_F_MS_NAME__1: 'Mash Out',
    STEP_TEMP__1: 76,
    _STEP_TIME__1: 10,
    MS_RISE_TIME__1: 10,
    MS_INFUSION_TEMP__1: '83,33',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Cheio - Mash por Temperatura, 2 Passos',
    MashStep_F_MS_NAME: 'Proteica',
    STEP_TEMP: '50,00',
    _STEP_TIME: 30,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '54,05',

    MashStep_F_MS_NAME__1: 'Sacarificação (β + α)',
    STEP_TEMP__1: 69,
    _STEP_TIME__1: 30,
    MS_RISE_TIME__1: 15,
    MS_INFUSION_TEMP__1: '105,11',
    __1: '',
    MashStep_F_MS_NAME__2: 'Mash Out',
    STEP_TEMP__2: '75,56',
    _STEP_TIME__2: 10,
    MS_RISE_TIME__2: 10,
    MS_INFUSION_TEMP__2: '83,33',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Leve - Mash por Temperatura, 2 Passos',
    MashStep_F_MS_NAME: 'Proteica',
    STEP_TEMP: '50,00',
    _STEP_TIME: 30,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '54,05',

    MashStep_F_MS_NAME__1: 'Sacarificação (β)',
    STEP_TEMP__1: 64,
    _STEP_TIME__1: 75,
    MS_RISE_TIME__1: 15,
    MS_INFUSION_TEMP__1: '105,11',
    __1: '',
    MashStep_F_MS_NAME__2: 'Mash Out',
    STEP_TEMP__2: '75,56',
    _STEP_TIME__2: 10,
    MS_RISE_TIME__2: 10,
    MS_INFUSION_TEMP__2: '83,33',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Médio - Mash por Temperatura, 2 Passos',
    MashStep_F_MS_NAME: 'Proteica',
    STEP_TEMP: '50,00',
    _STEP_TIME: 30,
    MS_RISE_TIME: 2,
    MS_INFUSION_TEMP: '54,05',

    MashStep_F_MS_NAME__1: 'Sacarificação (β + α)',
    STEP_TEMP__1: 67,
    _STEP_TIME__1: 45,
    MS_RISE_TIME__1: 15,
    MS_INFUSION_TEMP__1: '105,11',
    __1: '',
    MashStep_F_MS_NAME__2: 'Mash Out',
    STEP_TEMP__2: '75,56',
    _STEP_TIME__2: 10,
    MS_RISE_TIME__2: 10,
    MS_INFUSION_TEMP__2: '83,33',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Cheio - BIAB',
    MashStep_F_MS_NAME: 'Sacarificação (β + α)',
    STEP_TEMP: '68,90',
    _STEP_TIME: 60,
    MS_RISE_TIME: 10,
    MS_INFUSION_TEMP: '76,51',

    MashStep_F_MS_NAME__1: 'Mash Out',
    STEP_TEMP__1: 76,
    _STEP_TIME__1: 10,
    MS_RISE_TIME__1: 7,
    MS_INFUSION_TEMP__1: '48,89',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Leve - BIAB',
    MashStep_F_MS_NAME: 'Sacarificação (β)',
    STEP_TEMP: '64,40',
    _STEP_TIME: 90,
    MS_RISE_TIME: 10,
    MS_INFUSION_TEMP: '71,28',

    MashStep_F_MS_NAME__1: 'Mash Out',
    STEP_TEMP__1: 76,
    _STEP_TIME__1: 10,
    MS_RISE_TIME__1: 7,
    MS_INFUSION_TEMP__1: '48,89',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'Corpo Médio - BIAB',
    MashStep_F_MS_NAME: 'Sacarificação (β + α)',
    STEP_TEMP: '66,70',
    _STEP_TIME: 75,
    MS_RISE_TIME: 10,
    MS_INFUSION_TEMP: '73,95',

    MashStep_F_MS_NAME__1: 'Mash Out',
    STEP_TEMP__1: 76,
    _STEP_TIME__1: 10,
    MS_RISE_TIME__1: 7,
    MS_INFUSION_TEMP__1: '48,89',
    __1: '',
    MashStep_F_MS_NAME__2: '',
    STEP_TEMP__2: '',
    _STEP_TIME__2: '',
    MS_RISE_TIME__2: '',
    MS_INFUSION_TEMP__2: '',
    __2: '',
    MashStep_F_MS_NAME__3: '',
    STEP_TEMP__3: '',
    _STEP_TIME__3: '',
    MS_RISE_TIME__3: '',
    MS_INFUSION_TEMP__3: '',
    __3: '',
    MashStep_F_MS_NAME__4: '',
    STEP_TEMP__4: '',
    _STEP_TIME__4: '',
    MS_RISE_TIME__4: '',
    MS_INFUSION_TEMP__4: '',
  },
  {
    MashName: 'BIAB, Pilsner',
    MashStep_F_MS_NAME: 'Acidificação',
    STEP_TEMP: '35,00',
    _STEP_TIME: 5,
    MS_RISE_TIME: 10,
    MS_INFUSION_TEMP: '37,09',

    MashStep_F_MS_NAME__1: 'Proteica',
    STEP_TEMP__1: 52,
    _STEP_TIME__1: 15,
    MS_RISE_TIME__1: 15,
    MS_INFUSION_TEMP__1: '48,89',
    __1: '',
    MashStep_F_MS_NAME__2: 'Sacarificação (β)',
    STEP_TEMP__2: '63,00',
    _STEP_TIME__2: 45,
    MS_RISE_TIME__2: 11,
    MS_INFUSION_TEMP__2: '48,89',
    __2: '',
    MashStep_F_MS_NAME__3: 'Sacarificação (α)',
    STEP_TEMP__3: '72,00',
    _STEP_TIME__3: 30,
    MS_RISE_TIME__3: 9,
    MS_INFUSION_TEMP__3: '48,89',
    __3: '',
    MashStep_F_MS_NAME__4: 'Mash Out',
    STEP_TEMP__4: '78,00',
    _STEP_TIME__4: 10,
    MS_RISE_TIME__4: 6,
    MS_INFUSION_TEMP__4: '48,89',
  },
];
